# Code Generated by ZenTest v. 4.0.0
#                 classname: asrt / meth =  ratio%
#              ShortCircuit:    0 /    3 =   0.00%

require 'test/unit' unless defined? $ZENTEST and $ZENTEST

class TestShortCircuit < Test::Unit::TestCase
  def test_get_redundant_resistors
    raise NotImplementedError, 'Need to write test_get_redundant_resistors'
  end

  def test_get_shortest_path
    raise NotImplementedError, 'Need to write test_get_shortest_path'
  end

  def test_lowest_load
    raise NotImplementedError, 'Need to write test_lowest_load'
  end

  def test_lowest_load_equals
    raise NotImplementedError, 'Need to write test_lowest_load_equals'
  end

  def test_redundant_resistors
    raise NotImplementedError, 'Need to write test_redundant_resistors'
  end

  def test_redundant_resistors_equals
    raise NotImplementedError, 'Need to write test_redundant_resistors_equals'
  end

  def test_shortest_path
    raise NotImplementedError, 'Need to write test_shortest_path'
  end

  def test_shortest_path_equals
    raise NotImplementedError, 'Need to write test_shortest_path_equals'
  end
end

# Number of errors detected: 9
